// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menu-translate-full'
  | 'pref-backend-token'
  | 'pref-clear-key'
  | 'pref-description'
  | 'pref-endpoint'
  | 'pref-endpoint-hint'
  | 'pref-engine'
  | 'pref-full-section'
  | 'pref-health-check'
  | 'pref-instant-provider'
  | 'pref-instant-section'
  | 'pref-instant-test'
  | 'pref-openai-endpoint'
  | 'pref-openai-key'
  | 'pref-openai-model'
  | 'pref-output-bilingual'
  | 'pref-output-mode'
  | 'pref-output-translated'
  | 'pref-provider-google'
  | 'pref-provider-openai'
  | 'pref-save'
  | 'pref-save-annotation'
  | 'pref-show-progress'
  | 'pref-target-language'
  | 'pref-title';
